@baseUrl = http://localhost:8080

### 1) Hello World
GET {{baseUrl}}/HelloWorld
Accept: text/plain

### 2) Criar usuario (valores fixos no controller)
POST {{baseUrl}}/users
Accept: application/json

### 3) Listar usuarios
GET {{baseUrl}}/users
Accept: application/json

POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "nome": "Emy",
  "email": "emy@email.com",
  "senha": "123456"
}