spring.application.name=techub
spring.datasource.url=jdbc:postgresql://localhost:5432/techub
spring.datasource.username=techub_user
spring.datasource.password=techub_pass
spring.jpa.hibernate.ddl-auto=update
server.port=3000